version: '3.1'

services:
  maria:
    image: mariadb:latest
    container_name: "ave-maria"
    restart: always
    ports:
      - "3306:3306"
#    volumes:
#      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
#      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
#      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ="Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
